### PR TITLE
Master

### PR DESCRIPTION
**Pull request by Quadrivium4**
# Hi Andrei,
## I changed a lot:
now it's completly responsive, readble and the code is a little cleaner.
maybe is better that your portfolio is 100% made by you,
but this maybe can teach you something,
Keep learning!

### CODE REVIEW

**Review by AndreiMorosanC — COMMENTED** [review]
thank you very much for taking the time to touch my code and teach me how to make the website renpossible.
I'll take a look at it and make a note of any changes.

**Comment by Quadrivium4** [comment]
You're welcome, I'm happy to help someone!

**Comment by Quadrivium4** [comment]
If you have some question about the code, or you have some problem, or an idea for an interesting project
contact me!

**Comment by AndreiMorosanC** [comment]
okey thank you

**Pull request closed without merging**
